services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_database
            MYSQL_USER: user
            MYSQL_PASSWORD: passsword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - my_network

volumes:
    mysql_data:
        driver: local

networks:
    my_network:
        driver: bridge
